# Generated by Django 2.2.2 on 2019-07-05 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='psts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com', to='posts.Post'),
        ),
    ]
