# Generated by Django 2.2.2 on 2019-08-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
