# Generated by Django 2.2.2 on 2019-08-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190803_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='psts',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.ManyToManyField(to='posts.Comment'),
        ),
    ]
