# Generated by Django 2.2.2 on 2019-08-03 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190803_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='follower',
        ),
        migrations.AddField(
            model_name='connection',
            name='follower',
            field=models.ManyToManyField(blank=True, null=True, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='connection',
            name='following',
        ),
        migrations.AddField(
            model_name='connection',
            name='following',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
