# Generated by Django 2.2.2 on 2019-08-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190803_1659'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlink',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userlink',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='userlink',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
        migrations.DeleteModel(
            name='UserLink',
        ),
    ]
