# Generated by Django 2.2.2 on 2019-08-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timeline',
            field=models.ImageField(blank=True, null=True, upload_to='timeline_pictures'),
        ),
    ]
